using Unity.Mathematics;

/// <summary>
/// Temporary impulse generated by one custom physics joint.
/// Stored in a native container during joint processing.
/// </summary>
public struct CustomPhysImpulse {
    public float3 linImp;
    public float3 angImp;
}
