using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;

/// <summary>
/// Authoring component for rigidbodies with joints.
/// </summary>
public class CustomPhysJntBodyAuthoring : MonoBehaviour {
    public class Baker : Baker<CustomPhysJntBodyAuthoring> {
        public override void Bake(CustomPhysJntBodyAuthoring authoring) {
            Entity entity = GetEntity(TransformUsageFlags.Dynamic);
            AddComponent(entity, new CustomPhysImpulseAccum());
        }
    }
}

/// <summary>
/// Stores accumulated impulses generated by custom physics joints.
/// Multiple joint entities can write to the same rigidbody's accumulator.
/// The physics velocity is modified once after all joints have been processed.
/// </summary>
public struct CustomPhysImpulseAccum : IComponentData {
    public float3 linImp;
    public float3 angImp;
}