using Unity.Entities;
using UnityEngine;
using Unity.Mathematics;

/// <summary>
/// Physics spring affecting the center of mass of the physics body.
/// NOTE: A physics object can only have one spring component and one target. To simulate multiple springs affecting
/// NOTE C: a physics body, you should calculate the total impulses caused by the theoretical springs
/// NOTE C: and then change spring target and physics body velocities accodringly.
/// </summary>
public class EcsPhysSpringAuthoring : MonoBehaviour {
    [Header("General")]
    [Tooltip("Completely disables forces applied by the spring.")]
    public bool springEnabled = true;

    [Header("Spring Target")]
    [Tooltip("Entity that contains EcsPhysSpringTgt.")]
    public EcsPhysSpringTgtAuthoring target;

    [Header("Linear Drive")]
    [Tooltip("Whether the linear target is active.")]
    public bool enableLinSpring = true;
    public float linSpring = 400;
    public float maxLinSpringForce = 99999;
    public float linVelMatchDamper = 20;
    public float maxLinVelMatchDamperForce = 99999;
    public float linDragDamper = 1;
    public float maxLinDragDamperForce = 99999;
    public float maxLinTotalForce = 99999;

    [Header("Angular Drive")]
    [Tooltip("Whether the angular target is active.")]
    public bool enableAngSpring = true;
    public float angSpring = 0.5f;
    public float maxAngSpringTq = 99999;
    public float angVelMatchDamper = 0.05f;
    public float maxAngVelMatchDamperTq = 99999;
    public float angDragDamper = 0.005f;
    public float maxAngDragDamperTq = 99999;
    public float maxTotalTq = 99999;

    /// <summary>
    /// DOTS NOTE: Baker class adds components to the entity based on the authoring MonoBehaviour.
    /// </summary>
    public class EcsPhysSpringBaker : Baker<EcsPhysSpringAuthoring> {
        public override void Bake(EcsPhysSpringAuthoring authoring) {
            // DOTS NOTE: TransformUsageFlags let's us optimize the entity's world space behavior - choose the most restrictive flag you need!
            Entity entity = GetEntity(TransformUsageFlags.None);
            Entity targetEntity = GetEntity(authoring.target, TransformUsageFlags.None);
            AddComponent(entity, new CustomPhysImpulseAccum());
            AddComponent(
                entity,
                new EcsPhysSpring {
                    enabled = authoring.springEnabled,
                    tgt = targetEntity,
                    enableLin = authoring.enableLinSpring,
                    linSpring = authoring.linSpring,
                    maxLinSpringForce = authoring.maxLinSpringForce,
                    linVelMatchDamper = authoring.linVelMatchDamper,
                    maxLinVelMatchDamperForce = authoring.maxLinVelMatchDamperForce,
                    linDragDamper = authoring.linDragDamper,
                    maxLinDragDamperForce = authoring.maxLinDragDamperForce,
                    maxLinTotalForce = authoring.maxLinTotalForce,
                    enableAng = authoring.enableAngSpring,
                    angSpring = authoring.angSpring,
                    maxAngSpringTq = authoring.maxAngSpringTq,
                    angVelMatchDamper = authoring.angVelMatchDamper,
                    maxAngVelMatchDamperTq = authoring.maxAngVelMatchDamperTq,
                    angDragDamper = authoring.angDragDamper,
                    maxAngDragDamperTq = authoring.maxAngDragDamperTq,
                    maxTotalTq = authoring.maxTotalTq,
                }
            );
        }
    }
}

/// <summary>
/// Custom physics spring. Requires a spring target component to work.
/// DOTS NOTE: Components are structs which only hold data.
/// </summary>
public struct EcsPhysSpring : IComponentData {
    public bool enabled;
    // DOTS NOTE: This is not a pointer, but a struct with entity index. In a system you can then:
        // [ReadOnly]
        // public ComponentLookup<EcsPhysSpringTgt> tgtLookup;
        // EcsPhysSpringTgt tgt = tgtLookup[spring.target];
    public Entity tgt;
    // Linear drive
    public bool enableLin;
    public float linSpring;
    public float maxLinSpringForce;
    public float linVelMatchDamper;
    public float maxLinVelMatchDamperForce;
    public float linDragDamper;
    public float maxLinDragDamperForce;
    public float maxLinTotalForce;
    // Angular drive
    public bool enableAng;
    public float angSpring;
    public float maxAngSpringTq;
    public float angVelMatchDamper;
    public float maxAngVelMatchDamperTq;
    public float angDragDamper;
    public float maxAngDragDamperTq;
    public float maxTotalTq;
}

/// <summary>
/// Stores accumulated impulses generated by custom physics springs.
/// Multiple spring entities can write to the same rigidbody's accumulator. TODO: This might be no longer true.
/// The physics velocity is modified once after all springs have been processed.
/// </summary>
public struct CustomPhysImpulseAccum : IComponentData {
    public float3 linImp;
    public float3 angImp;
}