using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;

/// <summary>
/// Authoring component for rigidbodies with springs.
/// </summary>
public class EcsPhysSpringBodyAuthoring : MonoBehaviour {
    public class Baker : Baker<EcsPhysSpringBodyAuthoring> {
        public override void Bake(EcsPhysSpringBodyAuthoring authoring) {
            Entity entity = GetEntity(TransformUsageFlags.Dynamic);
            AddComponent(entity, new CustomPhysImpulseAccum());
        }
    }
}

/// <summary>
/// Stores accumulated impulses generated by custom physics springs.
/// Multiple spring entities can write to the same rigidbody's accumulator.
/// The physics velocity is modified once after all springs have been processed.
/// </summary>
public struct CustomPhysImpulseAccum : IComponentData {
    public float3 linImp;
    public float3 angImp;
}