using Unity.Mathematics;

/// <summary>
/// Temporary impulse generated by one custom physics spring.
/// Stored in a native container during spring processing.
/// </summary>
public struct EcsPhysSpringImp {
    public float3 linImp;
    public float3 angImp;
}
