using Unity.Entities;
using UnityEngine;
using Unity.Mathematics;

/// <summary>
/// Physics spring affecting the center of mass of the physics body.
/// NOTE: A physics object can only have one spring component and one target. To simulate multiple springs affecting
/// NOTE C: a physics body, you should calculate the total impulses caused by the theoretical springs
/// NOTE C: and then change spring target and physics body velocities accodringly.
/// </summary>
public class EcsPhysSpringAuthoring : MonoBehaviour {
    [Header("General")]
    [Tooltip("Completely disables forces applied by the spring.")]
    public bool springEnabled = true;

    [Header("Spring Target")]
    [Tooltip("Entity that contains EcsPhysSpringTgt.")]
    public EcsPhysSpringTgtAuthoring target;

    [Header("Linear Drive")]
    [Tooltip("Whether the linear target is active.")]
    public bool enableLinear = true;
    public float linearSpring = 20;
    public float linearDamper = 1;
    public float maxForce = 99999;

    [Header("Angular Drive")]
    [Tooltip("Whether the angular target is active.")]
    public bool enableAngular = true;
    public float angularSpring = 10;
    public float angularDamper = 1;
    public float maxTorque = 99999;

    /// <summary>
    /// DOTS NOTE: Baker class adds components to the entity based on the authoring MonoBehaviour.
    /// </summary>
    public class EcsPhysSpringBaker : Baker<EcsPhysSpringAuthoring> {
        public override void Bake(EcsPhysSpringAuthoring authoring) {
            // DOTS NOTE: TransformUsageFlags let's us optimize the entity's world space behavior - choose the most restrictive flag you need!
            Entity entity = GetEntity(TransformUsageFlags.None);
            Entity targetEntity = GetEntity(authoring.target, TransformUsageFlags.None);
            AddComponent(entity, new CustomPhysImpulseAccum());
            AddComponent(
                entity,
                new EcsPhysSpring {
                    enabled = authoring.springEnabled,
                    tgt = targetEntity,
                    linSpring = authoring.linearSpring,
                    linDamper = authoring.linearDamper,
                    maxForce = authoring.maxForce,
                    angSpring = authoring.angularSpring,
                    angDamper = authoring.angularDamper,
                    maxTq = authoring.maxTorque,
                    enableLin = authoring.enableLinear,
                    enableAng = authoring.enableAngular
                }
            );
        }
    }
}

/// <summary>
/// Custom physics spring. Requires a spring target component to work.
/// DOTS NOTE: Components are structs which only hold data.
/// </summary>
public struct EcsPhysSpring : IComponentData {
    public bool enabled;
    // DOTS NOTE: This is not a pointer, but a struct with entity index. In a system you can then:
        // [ReadOnly]
        // public ComponentLookup<EcsPhysSpringTgt> tgtLookup;
        // EcsPhysSpringTgt tgt = tgtLookup[spring.target];
    public Entity tgt;
    // Linear drive
    public float linSpring;
    public float linDamper;
    public float maxForce;
    // Angular drive
    public float angSpring;
    public float angDamper;
    public float maxTq;
    // Enable flags
    public bool enableLin;
    public bool enableAng;
}

/// <summary>
/// Stores accumulated impulses generated by custom physics springs.
/// Multiple spring entities can write to the same rigidbody's accumulator. TODO: This might be no longer true.
/// The physics velocity is modified once after all springs have been processed.
/// </summary>
public struct CustomPhysImpulseAccum : IComponentData {
    public float3 linImp;
    public float3 angImp;
}